services:
  mysql:
    image: mysql:8.0
    container_name: mysql-linkedin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ofertas_db
      MYSQL_USER: jnr
      MYSQL_PASSWORD: jnr123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql_data:
